### ISSUE TITLE
Need to refresh once after visiting site in Chrome

### ISSUE THREAD

**Issue by jorgebucaran** [maxogden/requirebin#124]
~Suddenly (and unfortunately) I seem to be unable to run any code.~

Visiting the site and opening the dev console I can see this and also I'm unable to run any code unless I refresh the browser at least once.

```
../../../../home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-pack/_prelude.js:1Not allowed to load local resource: blob:http://requirebin.com/26cc88c8-e53b-4fce-825c-d34da7c1a668
```

😢

**Comment by techdubb** [comment]
Looks to be specific to Chrome. Firefox is still working for me.

I'll try to take a look at it if I have a moment.

**Comment by jorgebucaran** [comment]
@h0ke Ah, you are totally right! It's cool 👋.

**Comment by techdubb** [comment]
@jbucaran this is kind of odd, but can you test something for me?

in chrome, go to requirebin.com and you'll observe the behavior you noted above.

but then, refresh once and let me know if it works.

**Comment by jbucaran** [comment]
Oh, it's alive! 🤖

I've updated the issue to reflect the problem, now that completely broken just sounds trollish 🙇.

Thanks! @h0ke
