### ISSUE TITLE
Error: CORS request rejected: https://wzrd.in/multi

### ISSUE THREAD

**Issue by balupton** [maxogden/requirebin#126]
[As wzrd.in is down](https://github.com/jfhbrook/wzrd.in/issues/165), requirebin is returning this error:

<img width="915" alt="screen shot 2017-04-01 at 5 00 57 am" src="https://cloud.githubusercontent.com/assets/61148/24569403/8257075a-1698-11e7-9d8c-8332fc4e9adf.png">

**Comment by techdubb** [comment]
Thanks for letting us know. 

As requirebin relies on wzrd.in, there's not much I can offer as a fix. It looks like @jfhbrook is on the case. 😄

**Comment by fabb** [comment]
Any news on this?

**Comment by Lucbug** [comment]
Wzrd.in is up, yet the CORS request is still rejected.

**Comment by KaKi87** [comment]
Hello,
I'm experiencing the same issue today :/
Thanks
