### ISSUE TITLE
Option for not minifying the source when saving.

### ISSUE THREAD

**Issue by joakin** [maxogden/requirebin#55]
Hi!

First, requirebin is awesome! Thanks for making it.

I've been playing with it, trying to make a little example, and tried to use the multiline package for creating some CSS and markdown in the source easily.

http://requirebin.com/?gist=33a10c722ec3dbc0374a

When trying the requirebin without saving everything works great since it it does not minify, but when saved, uglify removes the comments breaking the example.

I've modified the gist to contain the unminified code, so that I can load it from url... bit of a hack.

It would be great if we could have an option when saving so that we don't minify the source.

**Comment by maurizzzio** [comment]
@joakin now that there're multiple editors you can actually move all the css to the head as an alternative solution

**Comment by joakin** [comment]
I've closed the PR and I'm closing the issue too given I don't have time to finish this up. Feel free to reopen if somebody is interested on it.
