### ISSUE TITLE
Node modules id'd by multiple slashes does not work 

### ISSUE THREAD

**Issue by jouni-kantola** [maxogden/requirebin#68]
The following gist runs fine locally with Browserify:
[Code with modules id'd be multiple slashes](https://gist.github.com/jouni-kantola/b23cd891cec5b69690ac)
If the same code is ran in RequireBin the message below is displayed (also, see attached image):
"Bundling error: 

Error: CORS request rejected: http://wzrd.in/multi" 

![screen shot 2015-01-17 at 00 27 24](https://cloud.githubusercontent.com/assets/2670127/5786272/99932eac-9de2-11e4-806e-b0dd629f1dc5.png)

**Comment by maxogden** [comment]
its possible this is related to https://github.com/jesusabdullah/browserify-cdn/pull/94

with this code:

```
var VText = require('virtual-dom/vnode')
```

I get:

```
Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: 3da22540-9ddc-11e4-8de0-5787d9382434 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'virtual-dom/vnode' from '/tmp/virtual-dom115017-13543-azi92q/node_modules/virtual-dom/vnode'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/virtual-dom115017-13543-azi92q


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jesusabdullah/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and he can
try to help you out.

Have a nice day!

```

**Comment by jouni-kantola** [comment]
Does the structure of multiple slashes, like: 'virtual-dom/vnode/vnode', imply there always should be a module called 'virtual-dom/vnode'? As I mentioned in the issue, the code from the gist is bundled OK locally.

**Comment by maxogden** [comment]
hmm yea I think this used to work but the change from @feross in that PR *may have* broken this use case

**Comment by feross** [comment]
@maxogden The file you required doesn't exist :) It should be:

```js
var VText = require('virtual-dom/vnode/vtext')
```

That makes the browserify error go away, but now there's a CORS error:

```
Bundling error: 

Error: CORS request rejected: http://wzrd.in/multi
```

No idea how my change could cause a CORS error. Did anything else change recently?

**Comment by h0ke** [comment]
The CORS error seems to be due to the fact that wzrd.in was returning a 502 (the term rejected is a bit confusing).

The fix has been applied on the browserify-cdn side: https://github.com/jesusabdullah/browserify-cdn/issues/95

Once that's deployed to wzrd.in, this ticket should be good to close.

**Comment by h0ke** [comment]
@jouni-kantola It seems that the fix has been deployed.  Can you retry to verify all is well?

**Comment by feross** [comment]
@h0ke Looks good to me. Just happy that it wasn't my PR that broke things! :sweat_smile:

**Comment by h0ke** [comment]
@feross It turned out to be part of your PR. But no worries, gotta break things occasionally in the name of progress!  :D https://github.com/jesusabdullah/browserify-cdn/issues/95#issuecomment-70432452

**Comment by feross** [comment]
@h0ke do'h! many thanks for fixing it up!

**Comment by jouni-kantola** [comment]
Everything seems to build and run fine now. Here's the gist that earlier couldn't be run or saved:
http://requirebin.com/?gist=2c11f3b9107fcf32401e

**Comment by h0ke** [comment]
Thanks for verifying. :smile_cat:

**Comment by Luiz-N** [comment]
@h0ke @jouni-kantola The cors error seems to have returned... http://requirebin.com/?gist=2c11f3b9107fcf32401e

Chrome won't even let me navigate to the site wzrd.in

**Comment by h0ke** [comment]
@maxogden it looks like the cert expired for wzrd.in on Wednesday.
