### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by jcblw** [maxogden/requirebin#69]
Im having some difficulty saving a gist pulic or private. Seems to be a CORS issue with the [gatekeeper](https://github.com/prose/gatekeeper) server the production site is using.

This is where its stopping
https://github.com/maxogden/requirebin/blob/master/index.js#L62

![screenshot from 2015-01-25 22 19 47](https://cloud.githubusercontent.com/assets/578259/5895995/2caf8770-a4e2-11e4-89ae-7b7db566fb5b.png)

Sorry if this is not the best place to file this issue. I can move it if there is a better place.

**Comment by h0ke** [comment]
@maxogden looks like the gatekeeper might be down.

**Comment by maxogden** [comment]
oops, my fault. fixing now

**Comment by maxogden** [comment]
ok fixed. I upgraded ubuntu on my server without thinking to upgrade dokku/docker :) hehehehe

**Comment by jcblw** [comment]
Thanks :beers:

**Comment by GCheung55** [comment]
The issue is back.
