### ISSUE TITLE
Update server to point to HTTPS version of wzrd.in

### ISSUE THREAD

**Issue by konklone** [maxogden/requirebin#70]
In requirebin's `bundle.js`, it overrides the `config.BROWSERIFYCDN` value to be `http://wzrd.in`:

![screenshot from 2015-01-26 21 31 29](https://cloud.githubusercontent.com/assets/4592/5912491/d9ac7b84-a5a2-11e4-827a-d48f198e6d19.png)

This looks to be overridden on the server, as `config.js` is set to `http://localhost:8000` in [version control](https://github.com/maxogden/requirebin/blob/master/config.js). So I can't submit a pull request.

POSTs over CORS are the one thing that will be unavoidably broken by forcing an HTTPS redirect for wzrd.in. Given wzrd.in's level of use, and the simple nature of the fix for others who may be doing using `browser-module-sandbox`, I think updating requirebin.com is the only blocker before flipping the switch on wzrd.in.

**Comment by konklone** [comment]
Sorry, I never stated the specific request: can you change the value for `BROWSERIFYCDN` from **http://wzrd.in** to **https://wzrd.in**?

**Comment by maxogden** [comment]
done & deployed

**Comment by konklone** [comment]
And wzrd.in now forces a redirect to HTTPS. Thanks for the assist, @maxogden!
