### ISSUE TITLE
Support babel.js

### ISSUE THREAD

**Issue by Dashed** [maxogden/requirebin#71]
This would be so awesome to have.

Right now I'm running ES6 code through REPL (https://babeljs.io/repl/) and pasting it into requirebin; which is a huge chore :(

**Comment by kumavis** [comment]
This could be achieved with top-level browserify transforms.
[BrowserifyCDN](https://github.com/jfhbrook/browserify-cdn) would need to be altered to take in an entry text and list of transforms+args.

**Comment by kumavis** [comment]
so there would be two issues on [BrowserifyCDN](https://github.com/jfhbrook/browserify-cdn):
* [enabling transforms](https://github.com/jfhbrook/browserify-cdn/issues/84)
* [enabling entry point text](https://github.com/jfhbrook/browserify-cdn/issues/97)

and that might request changing http request semantics, etc etc, its an uphill battle.
If @maxogden wanted to add this feature directly, b/c its "still javascript" (coffeescript support was denied) well, it could be done.
But it also seems a little out of the scope of the project.

Thanks for the suggestion!

**Comment by maxogden** [comment]
sorry, yea it's outside of the scope for requirebin. also all of the es6 transpiler stuff has been such a time sink (so many bugs!) for me over the last ~1 year I've decided to wait for that ecosystem to calm down a bit before trying to support it in any projects

**Comment by kumavis** [comment]
makes sense. sorry @Dashed. I'm leaving the issues on browserifyCDN open so we'll see how that conversation progresses.

**Comment by Dashed** [comment]
No problem.

Thanks for the consideration.

**Comment by ianobermiller** [comment]
> I've decided to wait for that ecosystem to calm down a bit before trying to support it in any projects

Babel seems to be a front-runner at this point in time. Maybe reconsider?

**Comment by flyswatter** [comment]
I just found myself here because I wanted to play with `yo-yo` in requirebin. Is babel ready for requirebin showtime?

**Comment by flyswatter** [comment]
Sorry, I had a different bug!  Template strings work!

**Comment by maurizzzio** [comment]
Check http://esnextb.in/ 👍
