### ISSUE TITLE
uri escaping issues (?)

### ISSUE THREAD

**Issue by kumavis** [maxogden/requirebin#75]
Noticed this when I opened the console:
```
Not allowed to load local resource: blob:http%3A//requirebin.com/4e99652a-6d6b-4c01-bd71-e679b7be0aa8
```

**Comment by maxogden** [comment]
hmm very weird. I see it too, but only when devTools is closed.... if I have devTools open it never logs.

in fact, I just noticed that it happens every time I open and close devTools...

**Comment by kumavis** [comment]
mysterious indeed

**Comment by kumavis** [comment]
i think this is unrelated to requirebin
