### ISSUE TITLE
Cannot save gist

### ISSUE THREAD

**Issue by maurizzzio** [maxogden/requirebin#76]
Whenever I try to save a new gist the url goes to: `http://localhost:5000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch`, I think it's because the Github oauth app you created for RequireBin has its redirect uri pointing to `localhost:5000` perhaps for testing purposes

**Comment by maxogden** [comment]
oh oops i think i have the wrong key checked into the `gh-pages` branch...

**Comment by maxogden** [comment]
OK should be ok now, i didn't catch this yesterday because I guess my browser was already authenticated for `requirebin.com`
