### ISSUE TITLE
requirebin is now standard JS style compliant

### ISSUE THREAD

**Issue by maxogden** [maxogden/requirebin#79]
opening + closing this as an FYI. I converted all the JS to work with `feross/standard` here: https://github.com/maxogden/requirebin/commit/5f4ba5099bd4f7e507f8ceba345508e855b657b3

I tested the app and everything looks good to me, but there might be subtle bugs I missed

also I just added @maurizzzio to collaborators. welcome! feel free to open/close issues and make/merge PRs, but ping the other collaborators before merging your own PRs or pushing to 'gh-pages'

**Comment by maurizzzio** [comment]
Alright thanks :smiley:

**Comment by kumavis** [comment]
+1
