### ISSUE TITLE
error #0 when requiring npm module

### ISSUE THREAD

**Issue by mheiber** [maxogden/requirebin#86]
I'm getting error #0 when trying to require an npm module that I made which works fine on Node: 

var Tabs=require('react-tabs-component');

Can you recommend a way to fix my module so it will work with requirebin? requirebin is so awesome and I would love to be able to demo the module using it.

I'm attaching a screenshot and pasting full error message below.

![screen shot 2015-03-22 at 10 55 14 pm](https://cloud.githubusercontent.com/assets/4691093/6773364/b1b93170-d0e6-11e4-849e-b4ec0b333245.png)

Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---

(logs uuid: 000b94a0-d108-11e4-9e4d-4b4dd82dfefe )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'reactify' from '/tmp/react-tabs-component115223-30353-h6lq8y/node_modules/react-tabs-component'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/react-tabs-component115223-30353-h6lq8y

---

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

```
https://github.com/jesusabdullah/browserify-cdn/issues
```

Include the ENTIRETY of the contents of this message, and he can
try to help you out.

Have a nice day!

**Comment by maurizzzio** [comment]
requirebin uses https://github.com/jfhbrook/browserify-cdn to create a browserify bundle and unfortunately the bundling process doesn't allow hooking transforms (you're trying to use the  `reactify` transform)

**Comment by maxogden** [comment]
@maurizzzio actually browserify-cdn does run transforms if they are in package.json. @mheiber just didn't add reactify to dependencies here https://github.com/mheiber/react-tabs-component/blob/3088723c4c8ae0aeff9322f1f16489ead921907b/package.json#L17

**Comment by maurizzzio** [comment]
I see, sorry for misleading
