### ISSUE TITLE
editors.bundle is undefined (cannot save gist)

### ISSUE THREAD

**Issue by kirbysayshi** [maxogden/requirebin#87]
Seeing an error in both Firefox and Chrome where clicking save gist (after authenticating with github) produces the following console error and then fails to save the gist:

Firefox:
```
TypeError: editors.bundle is undefined     bundle.js:1:4312
```

Chrome:
```
Uncaught TypeError: Cannot read property 'editor' of undefined  bundle.js:1
fb9e0414-9358-4e0d-b12a-67b70d492914:1 Not allowed to load local resource: blob:http%3A//requirebin.com/fb9e0414-9358-4e0d-b12a-67b70d492914
```

Saving to gist thus seems to be broken at the moment.

**Comment by maurizzzio** [comment]
sorry about that, thanks for noticing :), I've deployed the fix

**Comment by kirbysayshi** [comment]
Yay! thanks so much! Glad it wasn't just me.
