### ISSUE TITLE
spins forever on startup in firefox (37)

### ISSUE THREAD

**Issue by gregglind** [maxogden/requirebin#88]
None of the upper right controls appear.

**Comment by kumavis** [comment]
do you have any plugins that might be interfering ?

**Comment by maurizzzio** [comment]
requirebin sets a default text for the editor which is stored in the following node:

```html
<script id="bundle-template" type="text/template">// require() some stuff from npm (like you were using browserify)
// and then hit Run Code to run it on the right
</script>
```

And then in index.js:

```javascript
```

**Comment by gregglind** [comment]
No.  From clean profile, observe:

1.  the 'pull down' list briefly appears, then disappears
2.  The throbber goes.
3.   14:16:06.069 TypeError: string is undefined  in  bundle.js:43:22020 .  

which is 
```
height+=lines[i].height}this.height=height}LeafChunk.prototype....
```

Hope that helps!

**Comment by maurizzzio** [comment]
I've uploaded the fix, tested it with Firefox 36

**Comment by gregglind** [comment]
Wow, that was fast!  It's a very cool product!

**Comment by kumavis** [comment]
@maurizzzio :fire: :fire_engine: :dash:  to the rescue

**Comment by maurizzzio** [comment]
thanks @gregglind for noticing the problem, indeed, it's a really cool project
