### ISSUE TITLE
Feature proposal: option to use URL parameters as source for sketch code instead of Gist

### ISSUE THREAD

**Issue by unframework** [maxogden/requirebin#96]
I.e. in addition to URLs like `http://requirebin.com/?gist=xyz123` support URLs like `http://requirebin.com/?rawJs=console.log(%27hello%27)%3B`

URLs have a size limit of about 2kb, which is actually quite enough for smaller code examples. As an extra feature later on, gzip+base64 filter could be added to up the size limit a bit.

This would be ideal for embedding runnable snippet links directly in README files, etc.

**Comment by maxogden** [comment]
this is kinda tricky to implement. right now we actually use gist as a CDN. when you publish a gist it saves the minified browserify bundle as `minified.js` on the gist, and when you view the embedded version it just does <script src="some url on github">. to support this we'd have to hit browserify-cdn for each embed request... which is theoretically doable but works differently than the current design

**Comment by unframework** [comment]
But what about when I type some code in without saving it to Gist and hit "run"? That doesn't do a round-trip to anything else does it? I can imagine a hypothetical patch just checking for that URL param and pre-initializing the textbox area with raw param value - everything else stays the same.

**Comment by maxogden** [comment]
oh right, I was thinking of the '/embed' feature, which wouldn't work with this proposal. if all you wanted to do was pre-populate the editor with some data it could be done

**Comment by unframework** [comment]
Sounds promising! I will take a peek at what's involved to get a PR submitted if you want.

**Comment by mikolalysenko** [comment]
+1 for this.  Also would like to be able to deep link code from github repos to avoid having to resync gists with the server.

**Comment by kumavis** [comment]
Looked up max url length, and while i couldnt find clear answers for modern browsers, as long as you're not on old IE, you have tens or hundreds of thousands of chars to play with

**Comment by maxogden** [comment]
@unframework yes please! also re: @mikolalysenko's suggestion it would be cool if you could either do `?code=<url encoded code>` or `?github=reponame/username/path/to/file.js`

**Comment by maxogden** [comment]
actually using `?code` might not be good since we use that for login (for the oauth dance). Maybe `?js=` would be better

**Comment by unframework** [comment]
The UI allows to edit several parts in a sketch: js, head, body, package.json. Makes sense to allow to specify some or all of those.

`?sketch.code=<xyz>&sketch.head=<xyz>&sketch.body=<xyz>&sketch.packageJson=<xyz>`

I checked the saved-gist structure and I know there are actually more parts stored there, but since this is just to pre-fill text fields, it should suffice.

**Comment by unframework** [comment]
Another convention for serializing multi-field params is:

`?sketch[code]=<xyz>&sketch[head]=<xyz>&sketch[body]=<xyz>&sketch[packageJson]=<xyz>`

**Comment by maurizzzio** [comment]
I've implemented the feature in cb55a1cf4f18f338baa71c7b2a13d7923093dc5e, I've used the convention suggested by @unframework which is `?sketch[code]=<xyz>&sketch[head]=<xyz>&sketch[body]=<xyz>&sketch[packageJson]=<xyz>`

Example: http://requirebin.com/?sketch[code]=var+functionPlot+%3D+require%28%27function-plot%27%29%0D%0AfunctionPlot%28%7B%0D%0A++target%3A+%27%23quadratic%27%2C%0D%0A++data%3A+%5B%7B%0D%0A++++fn%3A+function+%28x%29+%7B%0D%0A++++++return+x+*+x%0D%0A++++%7D%0D%0A++%7D%5D%0D%0A%7D%29&sketch[body]=%3Cspan+id%3D%22quadratic%22%3E%3C%2Fspan%3E%0D%0A%3Cscript+src%3D%22https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fd3%2F3.5.5%2Fd3.min.js%22%3E%3C%2Fscript%3E

**Comment by maxogden** [comment]
wow!

**Comment by kumavis** [comment]
url shortening service as free db

**Comment by unframework** [comment]
@maurizzzio looks great, thanks a lot! @kumavis - exactly, URL shorteners are like simple key-value stores.
